version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
  slack: circleci/slack@1.0.0
#  aws-code-deploy: circleci/aws-code-deploy@0.09
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/graphql
    steps:
      - checkout # ソースコードを引っ張ってくる
      - restore_cache: # `build.gradle` が変更されている場合に、保存されているキャッシュを復元
          key: graphql-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew assemble
      - save_cache: # 依存関係のキャッシュ
          paths:
            - ~/.gradle
          key: graphql-{{ checksum "build.gradle" }}
      - store_artifacts: # アーティファクトへの保存
          path: build/libs
      - aws-s3/sync: # jarをs3にアップロードする
          from: build/libs
          to: 's3://wever-content-artifact'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          overwrite: true
